version: '3'
services:
  database: 
    image: "influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
  dashboard: 
    image: "grafana/grafana"
    ports:
      - "3001:3000"
    depends_on: 
      - "database"